apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "gitlab.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  http:
    - route:
        - destination:
            host: gitlab-webservice-default.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8181
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-kas-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "kas.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  http:
    - route:
        - destination:
            host: gitlab-kas.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8154
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-shell-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "gitlab.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  tcp:
    - match:
        - port: 22
      route:
        - destination:
            host: gitlab-gitlab-shell.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ include "gitlab.shell.port" . | int }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-registry-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "registry.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  http:
    - route:
        - destination:
            host: gitlab-registry.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 5000
