apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-kas-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "kas.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  http:
    - route:
        - destination:
            host: gitlab-kas.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8154
