apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kafka-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  tcp:
  {{- range $idx, $_ := until (int .Values.broker.replicaCount) }}
    - match:
        - port: {{ add 9092 $idx }}
      route:
        - destination:
            host: {{ printf "%s-broker-%d-external" (include "common.names.fullname" $) $idx }}.{{ $.Release.Namespace }}.svc.cluster.local
            port:
              number: 9092
  {{- end }}
