apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "gitlab.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  tcp:
    - match:
        - port: 22
      route:
        - destination:
            host: gitlab-shell.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 22
