apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gitlab-registry-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ printf "registry.%s" .Values.global.hosts.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  tcp:
    - route:
        - destination:
            host: gitlab-registry.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 5000
