apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: postgres-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  tcp:
    - route:
      - destination:
          host: {{ include "cloudnative-pg.fullname" . }}-rw.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 5432
