apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: redis-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: {{ template "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 6379
    - match:
        - port: 16379
      route:
        - destination:
            host: {{ template "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 16379