apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tls.secretName }}
      hosts:
        - "*"
    - port:
        number: 22
        name: tcp-ssh
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 5432
        name: tcp-postgres
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 6379
        name: tcp-redis
        protocol: TCP
      hosts:
        - "*"