apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingress
  servers:
    {{- range $idx, $target := .Values.service.ports | default (list) }}
    - port:
        name: {{ $target.name | default (printf "port-%d" $idx) }}
        number: {{ $target.port }}
        protocol:
          {{- if eq (int ($target.port | default 0)) 80 }} HTTP
          {{- else if eq (int ($target.port | default 0)) 443 }} HTTPS
          {{- else }} TCP
          {{- end }}
      {{- if eq (int ($target.port | default 0)) 443 }}
      tls:
        mode: SIMPLE
        credentialName: {{ include "gateway.tlsSecretName" $ }}
      {{- else if eq (int ($target.port | default 0)) 80 }}
      tls:
        httpsRedirect: true
      {{- end }}
      hosts:
        - "*"
    {{- end }}

    {{- range $idx, $target := .Values.global.ports | default (list) }}
    - port:
        name: {{ $target.name | default (printf "port-%d" $idx) }}
        number: {{ $target.port }}
        protocol:
          {{- if eq (int ($target.port | default 0)) 80 }} HTTP
          {{- else if eq (int ($target.port | default 0)) 443 }} HTTPS
          {{- else }} TCP
          {{- end }}
      hosts:
        - "*"
    {{- end }}
