apiVersion: batch/v1
kind: Job
metadata:
  name: post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: post-install
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - kubectl label namespace {{ .Release.Namespace }} istio.io/dataplane-mode=ambient --overwrite
      restartPolicy: Never