apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: argocd-destination-rule
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ template "argo-cd.server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE