apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ template "argo-cd.server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 443
