apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kiali-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.gateway.target }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.cr.spec.deployment.instance_name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 20001
